import { Level, LevelType } from "../copmonents/custom-forms/level-form";

export interface TaskLink {
  taskSetSpaceCode: string;
  taskCode: string;
}

export interface Task {
  taskSetSpaceCode: string;
  code: string;
  name: string;
  levelType: LevelType;
  startExpression: string;
  goalType: string;
  goalExpression: string;
  goalNumberProperty: number;
  goalPattern: string;
  subjectTypes: string;
  additionalPacks: string;
  customLevelPack: string;
  expectedSteps: number;
  expectedTime: number;
  levelNameEn: string;
  levelNameRu: string;
  levelCode: string;
  autoGeneratedLevelsCount: number;
  operations: string;
  stepsCountInterval: string;
  implicitTransformationsCount: number;
}

export const mockTasks: {
  [code: string]: Level;
} = {
  "1": {
    // taskSetSpaceCode: "demo task set space code",
    // code: "1",
    name: "demo task",
    levelType: LevelType.MANUAL,
    startExpression: "2+2",
    goalType: "Сведение к целевому выражению",
    goalExpression: "4",
    goalNaturalNumber: 0,
    // goalPattern: "",
    subjectTypes: "demo",
    additionalPacks: "",
    customLevelPack: "",
    expectedSteps: 0,
    expectedTime: 0,
    levelNameEn: "",
    levelNameRu: "",
    levelCode: "",
    autoGeneratedLevelsCount: 0,
    operations: "",
    stepsCountInterval: "",
    implicitTransformationsCount: 0,
  },
  "2": {
    // taskSetSpaceCode: "demo task set space code",
    // code: "2",
    name: "demo task",
    levelType: LevelType.MANUAL,
    startExpression: "2+2",
    goalType: "Сведение к целевому выражению",
    goalExpression: "4",
    goalNaturalNumber: 0,
    // goalPattern: "",
    subjectTypes: "demo",
    additionalPacks: "",
    customLevelPack: "",
    expectedSteps: 0,
    expectedTime: 0,
    levelNameEn: "",
    levelNameRu: "",
    levelCode: "",
    autoGeneratedLevelsCount: 0,
    operations: "",
    stepsCountInterval: "",
    implicitTransformationsCount: 0,
  },
};

export default mockTasks;
