import { LevelType } from "../copmonents/custom-forms/level-form";

export interface TaskLink {
  taskSetSpaceCode: string;
  taskCode: string;
}

export interface Task {
  taskSetSpaceCode: string;
  code: string;
  nameEn: string;
  nameRu: string;
  levelType: LevelType;
  startExpression: string;
  goalType: string;
  goalExpression: string;
  goalNumberProperty: number;
  goalPattern: string;
  subjectTypes: string;
  additionalPacks: string;
  customLevelPack: string;
  expectedSteps: number;
  expectedTime: number;
  levelNameEn: string;
  levelNameRu: string;
  levelCode: string;
  autoGeneratedLevelsCount: number;
  operations: string;
  stepsCountInterval: string;
  implicitTransformationsCount: number;
}

const mockTasks: Task[] = [
  {
    taskSetSpaceCode: "demo task set space code",
    code: "123",
    nameEn: "demo task",
    nameRu: "демо задача",
    levelType: LevelType.MANUAL,
    startExpression: "2+2",
    goalType: "Сведение к целевому выражению",
    goalExpression: "4",
    goalNumberProperty: 0,
    goalPattern: "",
    subjectTypes: "demo",
    additionalPacks: "",
    customLevelPack: "",
    expectedSteps: 0,
    expectedTime: 0,
    levelNameEn: "",
    levelNameRu: "",
    levelCode: "",
    autoGeneratedLevelsCount: 0,
    operations: "",
    stepsCountInterval: "",
    implicitTransformationsCount: 0,
  },
];

export default mockTasks;
