import { TaskSetConstructorInputs } from "./task-set-constructor.types";
import { taskConstructorDefaultValues } from "./task-set-constructor.data";
import { MathInputFormat } from "../../utils/kotlin-lib-functions";

export const mockTaskSets: {
  [code: string]: TaskSetConstructorInputs;
} = {
  "1": {
    namespace: "Space code 1",
    code: "code_1",
    nameEn: "Mock task set 1",
    nameRu: "Сложный интересный набор задач",
    tasks: [
      {
        ...taskConstructorDefaultValues,
      },
      {
        ...taskConstructorDefaultValues,
      },
      {
        ...taskConstructorDefaultValues,
      },
      {
        ...taskConstructorDefaultValues,
      },
      {
        ...taskConstructorDefaultValues,
      },
    ],
  },
  "2": {
    namespace: "Space code 2",
    code: "code_2",
    nameEn: "Mock task set 2",
    nameRu: "Легкие задачи",
    tasks: [
      // {
      //   namespace: "демо ns",
      //   code: "3",
      //   nameEn: "demo task 3",
      //   nameRu: "демо бета тест",
      //   taskCreationType: "manual",
      //   startExpression: "3+3",
      //   goalType: "Сведение к целевому выражению",
      //   goalExpression: "6",
      //   goalNumberProperty: 0,
      //   goalPattern: "",
      //   // goalPattern: "",
      //   subjectTypes: "demo",
      //   additionalPacks: "",
      //   customLevelPack: "",
      //   expectedSteps: 0,
      //   expectedTime: 0,
      //   levelCode: "",
      //   autoGeneratedLevelsCount: 0,
      //   operations: "",
      //   stepsCountInterval: "",
      //   implicitTransformationsCount: 0,
      // },
      // {
      //   namespace: "демо ns",
      //   code: "2",
      //   nameEn: "demo task",
      //   nameRu: "задачка",
      //   taskCreationType: "manual",
      //   startExpression: "3+3",
      //   goalType: "Сведение к целевому выражению",
      //   goalExpression: "6",
      //   goalNumberProperty: 0,
      //   goalPattern: "",
      //   // goalPattern: "",
      //   subjectTypes: "demo",
      //   additionalPacks: "",
      //   customLevelPack: "",
      //   expectedSteps: 0,
      //   expectedTime: 0,
      //   levelCode: "",
      //   autoGeneratedLevelsCount: 0,
      //   operations: "",
      //   stepsCountInterval: "",
      //   implicitTransformationsCount: 0,
      // },
    ],
  },
  "3": {
    namespace: "Space code 3",
    code: "code_3",
    nameEn: "Mock task set 3",
    nameRu: "Подготовка к ЕГЭ",
    tasks: [
      // {
      //   namespace: "задачи для кр",
      //   code: "3",
      //   nameEn: "demo task 3",
      //   nameRu: "демо бета тест",
      //   taskCreationType: "manual",
      //   startExpression: {
      //     format: MathInputFormat.TEX,
      //     expression: ""
      //   },
      //   goalType: "Сведение к целевому выражению",
      //   goalExpression: {
      //     format: MathInputFormat.TEX,
      //     expression: ""
      //   },
      //   goalNumberProperty: 0,
      //   goalPattern: "",
      //   // goalPattern: "",
      //   subjectTypes: "demo",
      //   additionalPacks: "",
      //   customLevelPack: "",
      //   expectedSteps: 0,
      //   expectedTime: 0,
      //   levelCode: "",
      //   autoGeneratedLevelsCount: 0,
      //   operations: "",
      //   stepsCountInterval: 0,
      //   implicitTransformationsCount: 0,
      // },
      // {
      //   namespace: "ns Ивана Иванова",
      //   code: "3",
      //   nameEn: "demo task 3",
      //   nameRu: "демо бета тест",
      //   taskCreationType: "manual",
      //   startExpression: {
      //     format: MathInputFormat.TEX,
      //     expression: ""
      //   },
      //   goalType: "Сведение к целевому выражению",
      //   goalExpression: {
      //     format: MathInputFormat.TEX,
      //     expression: ""
      //   },
      //   goalNumberProperty: 0,
      //   goalPattern: "",
      //   // goalPattern: "",
      //   subjectTypes: "demo",
      //   additionalPacks: "",
      //   customLevelPack: "",
      //   expectedSteps: 0,
      //   expectedTime: 0,
      //   levelCode: "",
      //   autoGeneratedLevelsCount: 0,
      //   operations: "",
      //   stepsCountInterval: 0,
      //   implicitTransformationsCount: 0,
      // },
    ],
  },
};
