export type TaskCreationType = "auto" | "manual";

export interface TaskConstructorInputs {
  taskCreationType?: "auto" | "manual";
  nameEn: string;
  nameRu: string;
  code: string;
  namespace: string;
  subjectTypes: string;
  startExpression: string;
  goalType: string;
  goalExpression: string;
  goalNumberProperty: number;
  goalPattern: string;
  rulePacks: string;
  stepsNumber: number;
  time: number;
  difficulty: number;
  solution: string;
  countOfAutoGeneratedTasks: number;
  operations: string;
  stepsCountInterval: number;
  implicitTransformationsCount: number;
  autoGeneratedRulePacks: string;
  lightWeightOperations: string;
  nullWeightOperations: string;
  startTime: string;
  endTime: string;
}

export interface TaskConstructorProps {
  index: number;
  defaultValue: any;
  taskCreationType: TaskCreationType;
  updateDemo: (index: number) => void;
  visualizationMode: "table" | "list";
  hidden?: boolean;
  updateName?: (index: number, newName: string) => void;
}
