import { RulePackLink } from "../rule-pack-constructor/rule-pack-constructor.types";
import { MathInputFormat } from "../../utils/kotlin-lib-functions";

export interface ExpressionInput {
  format: MathInputFormat;
  expression: string;
}

export enum GoalType {
  CUSTOM = "CUSTOM",
  EXPRESSION = "EXPRESSION",
  COMPUTATION = "COMPUTATION",
  SIMPLIFICATION = "SIMPLIFICATION",
  CNF = "CNF",
  DNF = "DNF",
  FACTORIZATION = "FACTORIZATION",
  UNKNOWN = "UNKNOWN",
}

export interface TaskConstructorProps {
  index: number;
  defaultValue: any;
  updateDemo: (index: number) => void;
  visualizationMode: "table" | "list";
  isRendered?: boolean;
  updateName?: (index: number, newName: string) => void;
  rulePacks: string[];
}

export interface TaskConstructorReceivedForm {
  taskCreationType: "manual" | "auto";
  namespaceCode: string;
  code: string;
  nameEn: string;
  nameRu: string;
  descriptionShortEn: string;
  descriptionShortRu: string;
  descriptionEn: string;
  descriptionRu: string;
  subjectType: string;
  originalExpressionStructureString: string;
  originalExpressionTex: string;
  originalExpressionPlainText: string;
  originalExpression: ExpressionInput;
  goalType: GoalType;
  goalExpressionStructureString: string;
  goalExpressionTex: string;
  goalExpressionPlainText: string;
  goalExpression: ExpressionInput;
  goalPattern: string;
  goalNumberProperty: number;
  rulePacks: RulePackLink[];
  stepsNumber: number;
  time: number;
  difficulty: number;
  solution: string;
  countOfAutoGeneratedTasks: number;
  operations: string;
  stepsCountIntervals: string;
  implicitTransformationsCount: string;
  autoGeneratedRulePacks: any;
  lightWeightOperations: string;
  nullWeightOperations: string;
  maxNumberOfAutogeneratedTasks: number;
  numberOfAutogeneratedTasksToSolve: number;
  rules: any;
  otherGoalData: any;
  otherCheckSolutionData: any;
  otherAwardData: any;
  otherAutoGenerationData: any;
  otherData: any;
  solutionsStepsTree: any;
  hints: any;
  interestingFacts: any;
  nextRecommendedTasks: any;
}

export interface TaskConstructorInputs {
  taskCreationType: "auto" | "manual";
  namespaceCode: string;
  code: string;
  nameEn: string;
  nameRu: string;
  descriptionShortEn: string;
  descriptionShortRu: string;
  descriptionEn: string;
  descriptionRu: string;
  subjectType: string;
  originalExpression: ExpressionInput;
  goalType: GoalType;
  goalExpression: ExpressionInput;
  goalPattern: string;
  goalNumberProperty: number;
  rulePacks: string[] | string;
  stepsNumber: number;
  time: number;
  difficulty: number;
  solution: ExpressionInput;
  countOfAutoGeneratedTasks: number;
  operations: string;
  stepsCountIntervals: string;
  implicitTransformationsCount: string;
  autoGeneratedRulePacks: any;
  lightWeightOperations: string;
  nullWeightOperations: string;
  maxNumberOfAutogeneratedTasks: number;
  numberOfAutogeneratedTasksToSolve: number;
  otherGoalData: any;
  otherCheckSolutionData: any;
  otherAwardData: any;
  otherAutoGenerationData: any;
  otherData: any;
  rules: any;
  solutionsStepsTree: string;
  hints: string;
  interestingFacts: string;
  nextRecommendedTasks: string;
}
