import { ConstructorJSONs } from "./constructor-jsons.types";
import { GoalType } from "../../utils/constructors-requests/fetch-constructors.types";
import { NamespaceGrantType } from "../../utils/constructors-requests/namespace-request-handler";

const CONSTRUCTOR_JSONS_INITIAL_STATE: ConstructorJSONs = {
  namespace: {
    code: "",
    allowRead: "true",
    grantType: NamespaceGrantType.PUBLIC_READ_PRIVATE_WRITE,
    writeGrantedUsers: "",
    readGrantedUsers: "",
  },
  rulePack: {
    code: "",
    nameEn: "",
    nameRu: "",
    namespaceCode: "",
    rulePacks: "",
    rules: [],
  },
  taskSet: {
    code: "",
    namespaceCode: "",
    nameEn: "",
    nameRu: "",
    subjectTypes: [],
    recommendedByCommunity: false,
    otherData: "",
    tasks: [
      {
        namespaceCode: "",
        code: "",
        nameEn: "",
        nameRu: "",
        subjectTypes: [],
        originalExpressionStructureString: "",
        originalExpressionTex: "",
        originalExpressionPlainText: "",
        goalType: GoalType.CUSTOM,
        goalExpressionStructureString: "",
        goalExpressionTex: "",
        goalExpressionPlainText: "",
        goalPattern: "",
        goalNumberProperty: 0,
        rulePacks: [],
        stepsNumber: 0,
        time: 0,
        difficulty: 0,
        solution: "",
        countOfAutoGeneratedTasks: 0,
        operations: "",
        stepsCountIntervals: "",
        implicitTransformationsCount: "",
        autoGeneratedRulePacks: [],
        lightWeightOperations: "",
        nullWeightOperations: "",
        maxNumberOfAutogeneratedTasks: 0,
        numberOfAutogeneratedTasksToSolve: 0,
        otherGoalData: "",
        otherCheckSolutionData: "",
        otherAwardData: "",
        otherAutogenerationData: "",
        otherData: "",
      },
    ],
  },
};

export default CONSTRUCTOR_JSONS_INITIAL_STATE;
