import { ConstructorJSONs } from "./constructor-jsons.types";
import { GoalType } from "../../constructors/task-constructor/task-constructor.types";
import { MathInputFormat } from "../../utils/kotlin-lib-functions";
import { NamespaceGrantType } from "../../constructors/namespace-constructor/namespace-constructor.types";

const CONSTRUCTOR_JSONS_INITIAL_STATE: ConstructorJSONs = {
  isNamespaceJSONValid: true,
  isRulePackJSONValid: true,
  isTaskSetJSONValid: true,
  namespace: {
    code: "",
    allowRead: "true",
    grantType: NamespaceGrantType.PUBLIC_READ_PRIVATE_WRITE,
    writeGrantedUsers: [],
    readGrantedUsers: [],
  },
  rulePack: {
    code: "",
    nameEn: "",
    nameRu: "",
    namespaceCode: "",
    rulePacks: [],
    rules: [],
  },
  taskSet: {
    code: "",
    namespaceCode: "",
    nameEn: "",
    nameRu: "",
    subjectTypes: [],
    recommendedByCommunity: false,
    otherData: "",
    tasks: [
      {
        taskCreationType: "manual",
        namespaceCode: "",
        code: "",
        nameEn: "",
        nameRu: "",
        subjectTypes: [],
        originalExpression: {
          format: MathInputFormat.TEX,
          expression: "",
        },
        goalType: GoalType.CUSTOM,
        goalExpression: {
          format: MathInputFormat.TEX,
          expression: "",
        },
        goalPattern: "",
        goalNumberProperty: 0,
        rulePacks: [],
        stepsNumber: 0,
        time: 0,
        difficulty: 0,
        solution: {
          format: MathInputFormat.TEX,
          expression: "",
        },
        countOfAutoGeneratedTasks: 0,
        operations: "",
        stepsCountIntervals: "",
        implicitTransformationsCount: "",
        autoGeneratedRulePacks: [],
        lightWeightOperations: "",
        nullWeightOperations: "",
        maxNumberOfAutogeneratedTasks: 0,
        numberOfAutogeneratedTasksToSolve: 0,
        otherGoalData: "",
        otherCheckSolutionData: "",
        otherAwardData: "",
        otherAutogenerationData: "",
        otherData: "",
      },
    ],
  },
};

export default CONSTRUCTOR_JSONS_INITIAL_STATE;
