import { AllLevelsHiddenFields } from "./levels-hidden-fields.types";

const HIDDEN_LEVELS_FIELDS_INITIAL_STATE: AllLevelsHiddenFields = {
  manualLevelsHiddenFields: {
    subjectTypes: false,
    additionalPacks: false,
    customLevelPack: false,
    expectedSteps: false,
    expectedTime: false,
    levelNameEn: false,
    levelNameRu: false,
    levelCode: false,
    autoGeneratedLevelsCount: false,
    operations: false,
    stepsCountInterval: false,
    implicitTransformationsCount: false,
  },
  autoLevelsHiddenFields: {
    startExpression: false,
    goalType: false,
    goalExpression: false,
    goalNaturalNumber: false,
    additionalPacks: false,
    customLevelPack: false,
    expectedSteps: false,
    expectedTime: false,
    levelNameEn: false,
    levelNameRu: false,
    levelCode: false,
  },
};

export default HIDDEN_LEVELS_FIELDS_INITIAL_STATE;
